import { Bot } from "lucide-react";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { AnalyzeButton } from "./analyze-button";
import type { ProductDetail } from "@/lib/products/detail-queries";

export function AIAnalysisPanel({
  productId,
  analysis,
}: {
  productId: string;
  analysis: ProductDetail["latestAnalysis"];
}) {
  return (
    <Card>
      <CardHeader className="flex-row items-center justify-between">
        <CardTitle className="flex items-center gap-2">
          <Bot className="size-4" />
          AI Product Analysis
        </CardTitle>
        <AnalyzeButton productId={productId} hasAnalysis={Boolean(analysis)} />
      </CardHeader>
      <CardContent>
        {!analysis ? (
          <p className="text-sm text-muted-foreground">
            Run an AI analysis to see why this product is trending, buyer psychology, competitive landscape, and a
            launch recommendation.
          </p>
        ) : (
          <div className="flex flex-col gap-5">
            <div className="flex items-center gap-2">
              <Badge variant={analysis.aiProvider === "DEMO" ? "outline" : "info"}>
                {analysis.aiProvider === "DEMO" ? "Demo analysis" : `Generated by ${analysis.aiProvider}`}
              </Badge>
              {analysis.confidenceScore !== null && (
                <span className="text-xs text-muted-foreground">AI confidence: {analysis.confidenceScore}/100</span>
              )}
            </div>

            <Section title="Overview" text={analysis.overview} />
            <Section title="Why it's trending" text={analysis.whyTrending} />

            <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
              <Section title="Consumer problem" text={analysis.consumerProblem} />
              <Section title="Target audience" text={analysis.targetAudience} />
              <Section title="Buyer psychology" text={analysis.buyerPsychology} />
              <Section title="Market maturity" text={analysis.marketMaturity} />
            </div>

            <div className="grid grid-cols-1 gap-5 sm:grid-cols-3">
              <Section title="TikTok potential" text={analysis.tiktokPotential} />
              <Section title="Instagram potential" text={analysis.instagramPotential} />
              <Section title="Meta Ads potential" text={analysis.metaAdsPotential} />
            </div>

            {analysis.risks.length > 0 && (
              <div>
                <h4 className="mb-1.5 text-xs font-semibold tracking-wide text-muted-foreground uppercase">Risks</h4>
                <ul className="list-inside list-disc space-y-1 text-sm text-muted-foreground">
                  {analysis.risks.map((risk, i) => (
                    <li key={i}>{risk}</li>
                  ))}
                </ul>
              </div>
            )}

            <div className="rounded-md border bg-muted/40 p-4">
              <h4 className="mb-1 text-xs font-semibold tracking-wide text-muted-foreground uppercase">
                Launch recommendation
              </h4>
              <p className="text-sm">{analysis.launchRecommendation}</p>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function Section({ title, text }: { title: string; text: string | null }) {
  if (!text) return null;
  return (
    <div>
      <h4 className="mb-1 text-xs font-semibold tracking-wide text-muted-foreground uppercase">{title}</h4>
      <p className="text-sm leading-relaxed">{text}</p>
    </div>
  );
}
